[package]
name = "kafcars-inner-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
darling = "0.20.10"
syn = "2.0.79"
proc-macro2 = "1.0.87"
quote = "1.0.37"
serde_json = "1.0.128"

[lib]
proc-macro = true
